title: Foodsoft@NL
tagline: open source software for foodcoops
description: >
  Documentation site for Foodsoft@NL, hosted and open source software for running a food cooperative.

avatar: https://avatars3.githubusercontent.com/u/4671816
twitter_username: foodsoftdev
github_username: foodcoop-adam
#external_link:
#  title: VoedselcollectiefNL
#  href: http://www.voedselcollectief.org/

timezone: Europe/Amsterdam

# Build settings
markdown: kramdown
highlighter: pygmenter

